repo_App/urls.py
from django.urls import path
from . import views

app_name = "repo_App"

urlpatterns = [
    # path('login/', views.signin, name='login'),
    #
    path('', views.home, name='home'),
    path('get_authors/', views.getAuthors, name='get_authors'),
    path('get_themes/', views.getThemes, name='get_themes'),

    path('documentos/', views.documents, name='documents'),

    path('videos/', views.videos, name='videos'),

    path('audios/', views.audios, name='audios'),

    path('imagenes/', views.images, name='images')
]

repo_DDM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('repo_App.urls')),
]

repo_App/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_professor = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

class Author(models.Model):
    name = models.CharField(max_length=250)

class Theme(models.Model):
    name = models.CharField(max_length=250)

class File(models.Model):
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    size = models.FloatField()
    date = models.DateField(null=True)
    up_date = models.DateTimeField(auto_now_add=True)
    format = models.CharField(max_length=5)
    authors = models.ManyToManyField(Author)
    themes = models.ManyToManyField(Theme)

    class Meta:
        abstract = True

class Document(File):
    resumen = models.TextField(max_length=2000)
    file = models.FileField(upload_to="files/documents")

class Video(File):
    duration = models.IntegerField(_(""))
    file = models.FileField(upload_to="files/videos")

class Audio(File):
    duration = models.DurationField(_(""))
    file = models.FileField(upload_to="files/audios")

class Image(File):
    dimensions = models.CharField(max_length=15)
    file = models.FileField(upload_to="files/images")

repo_App/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import *


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("email",)

repo_App/views.py
from django.shortcuts import render
from .models import *
from django.http import JsonResponse
from django.core.paginator import Paginator


# Create your views here.
def getAuthors(request):
    authors = Author.objects.all()
    paginator = Paginator(authors, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    authors_list = [{'id': author.id, 'name': author.name} for author in page_obj]

    return JsonResponse({'authors': authors_list,
                         'has_previous': page_obj.has_previous(),
                         'has_next': page_obj.has_next(),
                         'previous_page_number': page_obj.previous_page_number() if page_obj.has_previous() else None,
                         'next_page_number': page_obj.next_page_number() if page_obj.has_next() else None,
                         })


def getThemes(request):
    themes = Theme.objects.all()
    paginator = Paginator(themes, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    themes_list = [{'id': theme.id, 'name': theme.name} for theme in page_obj]

    return JsonResponse({'themes': themes_list,
                         'has_previous': page_obj.has_previous(),
                         'has_next': page_obj.has_next(),
                         'previous_page_number': page_obj.previous_page_number() if page_obj.has_previous() else None,
                         'next_page_number': page_obj.next_page_number() if page_obj.has_next() else None,
                         })


def getDocuents(request):
    documents = Document.objects.all()
    paginator = Paginator(documents, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    documents_list = [{'id': document.id, 'title': document.title, 'size': document.size, 'resumen': document.resumen,
                       'date': document.date} for document in page_obj]

    return JsonResponse({'documents': documents_list,
                         'has_previous': page_obj.has_previous(),
                         'has_next': page_obj.has_next(),
                         'previous_page_number': page_obj.previous_page_number() if page_obj.has_previous() else None,
                         'next_page_number': page_obj.next_page_number() if page_obj.has_next() else None,
                         })


def home(request):
    # authors_list = getAuthors(request)
    return render(request, "repo_App/home/home.html", )


def documents(request):
    documents_list = Document.objects.all()
    if request.method == 'GET':
        return render(request, "repo_App/documents/documents.html", {'documents': documents_list})

    if request.method == 'POST':
        document = Document
        title = request.GET.get('title')
        description = request.GET.get('description')
        size = request.GET.get('size')
        resumen = request.GET.get('resumen')
        file = request.GET.get('file')
        date = request.GET.get('date')

        document(title=title, description=description, size=size, resumen=resumen, file=file, date=date)
        document.save
        return render(request, "repo_App/documents/documents.html", {'documents': documents_list})






def videos(request):
    return render(request, "repo_App/videos/videos.html")


def audios(request):
    return render(request, "repo_App/audios/audios.html")


def images(request):
    return render(request, "repo_App/images/images.html")

templates/repo_App/audios/audios.html
{% extends "repo_App/base.html" %}

{% block main %}
    <div class="welcome d-flex justify-content-center">
        <h4>Audios</h4>
    </div>

    <div class="line bg-success"></div>
{% endblock %}

templates/repo_App/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'repo_App/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'repo_App/mycss/base.css' %}">
    {% block styles %}

    {% endblock %}

    {% block title %}
    	<title>Repositorio DEM - Inicio</title>
    {% endblock %}

</head>
<body>
<header class="header-content position-fixed w-100 shadow-sm ">
     {% block header %}
        {% include 'repo_App/shared/header.html' %}
    {% endblock %}


    {% block  navigation %}
    	{% include 'repo_App/shared/navigation.html' %}
    {% endblock %}
</header>

<section class="main-content d-flex justify-content-center w-100">
    <div class="container bg-light shadow-sm p-4">
        {% block main %}

        {% endblock %}
    </div>

</section>

<footer class="position-fixed bottom-0 bg-dark w-100 d-flex justify-content-center align-items-center">
    <div>
        <p style="color: white; margin: 10px">Universidad de Ciencias Informaticas</p>
    </div>
</footer>

<script src="{% static 'repo_App/js/jquery.js' %}"></script>
<script src="{% static 'repo_App/js/bootstrap.min.js' %}"></script>

{% block script %}

{% endblock %}

</script>
</body>
</html>

templates/repo_App/documents/documents.html
{% extends "repo_App/base.html" %}

{% block main %}
    <div class="welcome d-flex justify-content-center">
        <h4>Documentos</h4>
    </div>

    <div class="line bg-success"></div>

    <div class="">
        <form class="form-control" action="/documentos/" method="post">
            {% csrf_token %}
            <div class="d-flex flex-column w-25">
                <label class="form-label" for="title">titulo</label>
                <input class="" type="text" name="title">
            </div>
            <div class="d-flex flex-column w-25">
                <label for="description">descripcion</label>
                <textarea type="text" name="description"></textarea>
            </div>
            <div class="d-flex flex-column w-25">
                <label for="size">Tamano</label>
                <input type="number" name="size">
            </div>
            <div class="d-flex flex-column w-25">
                <label for="resumen">Resumen</label>
                <textarea type="text" name="resumen"></textarea>
            </div>
            <div class="d-flex flex-column w-25">
                <label for="file">Archivo</label>
                <input type="file" name="file">
            </div>
            <div class="d-flex flex-column w-25">
                <label for="file">Archivo</label>
                <input type="date" name="file">
            </div>
            <div>
                <button class="button" type="submit">Enviar</button>
            </div>

        </form>
    </div>

    <div class="d-flex">

        {% for document in documents %}
        	<div class="document-card row">
            <div>
                Imagen
            </div>
            <div class="">
                {{ document.title }}
            </div>

        </div>
        {% endfor %}



    </div>

{% endblock %}

{% block script %}
{#    <script>#}
{#        $(document).ready(function () {#}
{#            function loadDocuments(document_page) {#}
{##}
{#                $.ajax({#}
{#                    url: '/get_document/',#}
{#                    type: 'GET',#}
{#                    dataType: 'json',#}
{#                    data: {'page': author_page},#}
{#                    success: function (response) {#}
{##}
{#                        $('#authors-list').empty();#}
{##}
{#                        $.each(response.authors, function (index, author) {#}
{#                            $('#authors-list').append('<div class="document-card">' +#}
{#                                #}
{#                                '<a class="link-success a-item" href="#">' + author.name + '</a>' +#}
{#                                '</div>');#}
{#                        });#}
{##}
{#                        updateAuthorPagination(response);#}
{#                    },#}
{#                    error: function (xhr, status, error) {#}
{#                        console.error(error);#}
{#                    }#}
{#                });#}
{#            }#}
{##}
{#            function updateAuthorPagination(response) {#}
{##}
{#                var previousLink = $('#previous-link-author');#}
{#                var nextLink = $('#next-link-author');#}
{##}
{#                if (response.has_previous) {#}
{#                    previousLink.attr('href', '?page=' + response.previous_page_number);#}
{#                    previousLink.show();#}
{#                } else {#}
{#                    previousLink.hide();#}
{#                }#}
{##}
{#                if (response.has_next) {#}
{#                    nextLink.attr('href', '?page=' + response.next_page_number);#}
{#                    nextLink.show();#}
{#                } else {#}
{#                    nextLink.hide();#}
{#                }#}
{#            }#}
{##}
{#            var urlParams = new URLSearchParams(window.location.search);#}
{#            var currentPage = urlParams.get('page');#}
{##}
{#            loadAuthors(currentPage);#}
{#        });#}
{#    </script>#}
{% endblock %}

templates/repo_App/home/home.html
{% extends 'repo_App/base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'repo_App/mycss/home.css' %}">
{% endblock %}
{% block main %}

    <div class="welcome d-flex justify-content-center">
        <h4>Repositorio Digital Inicio</h4>
    </div>

    <div class="line bg-success"></div>

    <div class="row mt-3">
        <div class="d-flex flex-wrap col-8 gap-2">
            <h5 class="w-100">Buscar por:</h5>
            <div class="finde-content">
                <div class="d-flex justify-content-center">Autor</div>
                <div class="find-list">
                    <ul id="authors-list" class="ul-content"></ul>
                    <div id="authors-pagination">
                        <a class="link-success" id="previous-link-author" href="#" style="display: none;">Anterior</a>
                        <a class="link-success" id="next-link-author" href="#" style="display: none;">Siguiente</a>
                    </div>
                </div>

            </div>
            <div class="finde-content">
                <div class="d-flex justify-content-center">Tematica</div>
                <div class="find-list flex-column">
                    <ul id="themes-list" class="ul-content"></ul>
                    <div id="themes-pagination">
                        <a class="link-success" id="previous-link-theme" href="#" style="display: none;">Anterior</a>
                        <a class="link-success" id="next-link-theme" href="#" style="display: none;">Siguiente</a>
                    </div>
                </div>
            </div>
            <div class="finde-content">
                <div class="d-flex justify-content-center">Fecha</div>
                <div class="find-list flex-column">
                    <ul class="ul-content">
                        <li class="li-content"><a class="link-success a-item" href="">Cualquier cosa por ahora</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="d-flex col-4 justify-content-center">
            <h5 class="w-100">Temas de Interes:</h5>
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {
            function loadAuthors(author_page) {

                $.ajax({
                    url: '/get_authors/',
                    type: 'GET',
                    dataType: 'json',
                    data: {'page': author_page},
                    success: function (response) {

                        $('#authors-list').empty();

                        $.each(response.authors, function (index, author) {
                            $('#authors-list').append('<li class="page-item li-content">' +
                                '<a class="link-success a-item" href="#">' + author.name + '</a>' +
                                '</li>');
                        });

                        updateAuthorPagination(response);
                    },
                    error: function (xhr, status, error) {
                        console.error(error);
                    }
                });
            }

            function updateAuthorPagination(response) {

                var previousLink = $('#previous-link-author');
                var nextLink = $('#next-link-author');

                if (response.has_previous) {
                    previousLink.attr('href', '?page=' + response.previous_page_number);
                    previousLink.show();
                } else {
                    previousLink.hide();
                }

                if (response.has_next) {
                    nextLink.attr('href', '?page=' + response.next_page_number);
                    nextLink.show();
                } else {
                    nextLink.hide();
                }
            }

            var urlParams = new URLSearchParams(window.location.search);
            var currentPage = urlParams.get('page');

            loadAuthors(currentPage);
        });
        $(document).ready(function () {
            function loadThemes(theme_page) {

                $.ajax({
                    url: '/get_themes/',
                    type: 'GET',
                    dataType: 'json',
                    data: {'page': theme_page},
                    success: function (response) {

                        $('#themes-list').empty();

                        $.each(response.themes, function (index, theme) {
                            $('#themes-list').append('<li class="page-item li-content">' +
                                '<a class="link-success a-item" href="#">' + theme.name + '</a>' +
                                '</li>');
                        });

                        updateThemePagination(response);
                    },
                    error: function (xhr, status, error) {
                        console.error(error);
                    }
                });
            }

            function updateThemePagination(response) {

                var previousLink = $('#previous-link-theme');
                var nextLink = $('#next-link-theme');

                if (response.has_previous) {
                    previousLink.attr('href', '?page=' + response.previous_page_number);
                    previousLink.show();
                } else {
                    previousLink.hide();
                }

                if (response.has_next) {
                    nextLink.attr('href', '?page=' + response.next_page_number);
                    nextLink.show();
                } else {
                    nextLink.hide();
                }
            }

            var urlParams = new URLSearchParams(window.location.search);
            var currentPage = urlParams.get('page');

            loadThemes(currentPage);
        });
    </script>
{% endblock %}

templates/repo_App/images/images.html
{% extends "repo_App/base.html" %}
{% block main %}
    <div class="welcome d-flex justify-content-center">
        <h4>Galeria</h4>
    </div>

    <div class="line bg-success"></div>

    </div>
{% endblock %}

templates/repo_App/shared/header.html
<div class="header-top row bg-success">
    <div class="logo-content">
        Aqui va un logo
    </div>
    <div class="user-content d-flex flex-column">
        <div>
            No esta autenticado
        </div>
        <div>
            Autenticarse
        </div>
    </div>
</div>

templates/repo_App/shared/navigation.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link{% if request.path == '/' %} active {% endif %}" aria-current="page" href="{% url 'repo_App:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link{% if request.path == '/documentos/' %} active {% endif %}" aria-current="page" href="{% url 'repo_App:documents' %}">Documentos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link{% if request.path == '/videos/' %} active {% endif %}" aria-current="page" href="{% url 'repo_App:videos' %}">Videos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link{% if request.path == '/audios/' %} active {% endif %}" aria-current="page" href="{% url 'repo_App:audios' %}">Audios</a>
        </li>
          <li class="nav-item">
          <a class="nav-link{% if request.path == '/imagenes/' %} active {% endif %}" aria-current="page" href="{% url 'repo_App:images' %}">Galería</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/repo_App/videos/videos.html
{% extends "repo_App/base.html" %}

{% block main %}
   <div class="welcome d-flex justify-content-center">
        <h4>Videos</h4>
    </div>

    <div class="line bg-success"></div>
{% endblock %}